name: Start Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*-beta*'
jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
     - uses: 'phantomcyber/dev-cicd-tools/github-actions/start-release@main'
       with:
         GITHUB_TOKEN: ${{ secrets.SOAR_APPS_TOKEN }}
